version: '2'
services:

  zammad-nginx:
    environment:
        - 'VIRTUAL_HOST=helpdesk.mainwebsolutions.de'
        - 'VIRTUAL_PORT=80'
        - 'LETSENCRYPT_HOST=helpdesk.mainwebsolutions.de'
        - 'LETSENCRYPT_EMAIL=info@mainwebsolutions.de'
    networks:
        - default